name: CMake Cross-Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest-xlarge, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake (macOS)
        if: runner.os == 'macOS'
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -S .
        working-directory: ${{ github.workspace }}

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir build
          cmake -B build -DCMAKE_BUILD_TYPE=Release -S .
        working-directory: ${{ github.workspace }}

      - name: Build
        run: cmake --build build --config Release
        working-directory: ${{ github.workspace }}

      - name: Test
        run: ctest --build-config Release
        working-directory: ${{ github.workspace }}/build
